Flickit-Platform-Dev/flickit-assessment

- .github/workflows/ci-cd.yml
- pom.xml
[ ] - Did you labeled the PR as 'In Review'?
> FAC-352:feature:Move repo to flickit platform dev

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/email/EmailAdapter.java
> FAC-387: Set from display name in emails

- flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/AddEvidenceUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/UpdateEvidenceUseCase.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/AddEvidenceUseCaseParamTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/UpdateEvidenceUseCaseParamTest.java
- flickit-assessment-data/src/main/resources/liquibase/changelog-0.18.xml
> FAC-364 Limit evidence description charater number

- flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/evidence/GetEvidenceListRestController.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCaseParamTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
[X] - Did you labeled the PR as 'In Review'?
> FAC-305:feature:Add user to get evidence list result

- flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
> FAC-407: Edit emial text

- flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answer/AnswerPersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
[X] - Did you labeled the PR as 'In Review'?
> FAC-307:feature:Add needed validation to submit answer service

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroup/ExpertGroupJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/expertgroupaccess/ExpertGroupAccessJpaRepository.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/expertgroupaccess/ExpertGroupAccessPersistenceJpaAdapter.java
> Fac 411 bug showing expired invitations

- flickit-advice-engine/src/test/java/org/flickit/assessment/advice/architecture/annotation/exceptionhandler/ExceptionHandlersOrderAnnotationArchUnitTest.java
- flickit-assessment-common/src/test/java/org/flickit/assessment/common/architecture/annotation/exceptionhandler/ExceptionHandlersOrderAnnotationArchUnitTest.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/exception/MissingServletRequestParameterExceptionHandler.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/architecture/annotation/exceptionhandler/ExceptionHandlersOrderAnnotationArchUnitTest.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/architecture/ExceptionHandlersOrderAnnotationArchUnitTest.java
> FAC-324 Add arch-unit tests for exception handlers @order annotation

- .github/workflows/ci-cd.yml
> FAC-429:fix:Change latest image tag to GitHub sha

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCaseParamTest.java
> FAC-430: Counting deleted assessment in space list

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
> FAC-434 Add a List of kit maturity levels to the service output

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireQuestionListServiceTest.java
> FAC-431-fix-Don't save confidence level for empty answer

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/assessment/LoadAssessmentListPort.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
- flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJoinResultView.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/AssessmentJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessment/UserAssessmentListItemView.java
> FAC-418:feature:Add manageable to new assessment list service

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributevalue/AttributeValueJpaRepository.java
> FAC-488:fix:Fix IncorrectResultSizeDataAccessException on CreateAdvice

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceWithCounters.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceWithDetails.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/persistence/space/SpacePersistenceJpaAdapter.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/space/GetSpaceListUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/out/space/LoadSpaceListPort.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/space/GetSpaceListService.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/GetSpaceListServiceTest.java
> FAC-450: add owner display name to list spaces

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
> FAC-455 Fix usage of partial of composite key in query

- flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/CreateExpertGroupRestController.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/expertgroup/UpdateExpertGroupRestController.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/CreateExpertGroupUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/expertgroup/UpdateExpertGroupUseCase.java
> FAC-457: Bug remove website field obligation from update expert group

- flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentresult/AssessmentResultPersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
> Fac 464 return maturity level from in get assessment service

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/users/space/SpaceJpaRepository.java
> FAC-467: Fix bug where spaces without assessments do not load

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapter.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/adapter/out/calculate/AssessmentCalculateInfoLoadAdapterTest.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
> FAC-466:feature:Add kitVersionId to AnswerOptionImpactJpaRepository.findAllByOptionIdInAndKitVersionId

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/answeroption/AnswerOptionJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/asnweroptionimpact/AnswerOptionImpactJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkit/AssessmentKitJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/assessmentkitdsl/KitDslJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/attribute/AttributeJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/kittag/KitTagJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/levelcompetence/LevelCompetenceJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/question/QuestionJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/subject/SubjectJpaRepository.java
> FAC-456: Format kit module queries

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessmentuserrole/AssessmentUserRolePersistenceJpaAdapter.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentuserrole/AssessmentUserRoleJpaRepository.java
> FAC-458:feature:Sort GetAssessmentUsersUseCase result by displayName

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
> FAC-461:feature:Add kitVersionId to EvidenceJpaRepository.findAssessentAttributeEvidencesByTypeOrderByLastModificationTimeDesc

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
- flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/email/EmailAdapter.java
> Fac 451 get app name from env var

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/tenant/GetTenantInfoRestController.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/tenant/GetTenantInfoUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/tenant/GetTenantInfoService.java
- flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
> FAC-479: Implement GetTenantInfoService

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/in/rest/tenant/GetTenantLogoRestController.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/tenant/GetTenantLogoUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/tenant/GetTenantLogoService.java
- flickit-assessment-users/src/test/resources/postman/flickit-assessment-users.postman_collection.json
> Fac 480 implement get tenant logo service

- flickit-assessment-data/src/main/resources/liquibase/changelog-0.14.xml
- flickit-assessment-data/src/main/resources/liquibase/changelog-0.17.xml
> FAC-477 Rename old sequence names

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
- flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
- flickit-assessment-common/src/main/resources/i18n/messages_en.properties
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
Reverts Flickit-Platform-Dev/flickit-assessment#68
> Revert "FAC-409: file type size limitation"

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
- flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
- flickit-assessment-common/src/main/resources/i18n/messages_en.properties
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
Reverts Flickit-Platform-Dev/flickit-assessment#106
> FAC-409: file type size limitation

- flickit-assessment-common/src/main/resources/i18n/core/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserRolesService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AssessmentUserRoleTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GetAssessmentUserRolesServiceTest.java
> FAC-468:feature:Add Assessor's Assistant role

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/AppSpecProperties.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/tenant/GetTenantLogoUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/tenant/GetTenantLogoService.java
> Fac 484 add favicon to tenant logo service

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
> add temp debug log add

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
> FAC-409: File content type check

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
> FAC-409: bug : change debug level to warn

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/assessment/AssessmentPersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentListItem.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetSpaceAssessmentListServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AssessmentMother.java
[] - Did you update the corresponding document?
> FAC-485:feature:Add viewable to AssessmentListItem

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupService.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureService.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/UpdateExpertGroupPictureServiceTest.java
> FAC-489: Remove content type validation from expert group picture

- flickit-assessment-data/src/main/resources/liquibase/changelog-0.23.xml
> FAC-496: Rename user_groups and user_permission tables

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentResponseDto.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/in/rest/assessment/GetAssessmentRestController.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/GetAssessmentUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/GetAssessmentServiceTest.java
- flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
> FAC-487: feat: Add manageable and viewable to the result of GetAssessmentService

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/ApplicationException.java
- flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/ValidationException.java
- flickit-assessment-common/src/main/java/org/flickit/assessment/common/exception/handler/ValidationExceptionHandler.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/CreateAssessmentServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/DeleteUserAssessmentRoleServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/GrantUserAssessmentRoleServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessmentuserrole/UpdateUserAssessmentRoleServiceTest.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/DeleteAssessmentKitServiceTest.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitdsl/UploadKitDSLServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/CreateExpertGroupServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroup/DeleteExpertGroupServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/expertgroupaccess/ConfirmExpertGroupInvitationServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/space/DeleteSpaceServiceTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/service/spaceuseraccess/LeaveSpaceServiceTest.java
> FAC-504: Create ApplicationException as runtime custom exceptions parent

- flickit-assessment-users/src/main/java/org/flickit/assessment/users/adapter/out/minio/MinioAdapter.java
> FAC-503: refactor: remove file not found exception completely

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/kitdsl/UploadKitDslService.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/kitdsl/UploadKitDSLServiceTest.java
> Fac 520 bug fix zip file support

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/questionimpact/QuestionImpactMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/Answer.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AttributeValue.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionImpact.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerOptionImpactTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AnswerTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/AttributeValueTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/domain/QuestionTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionImpactMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AnswerOptionMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/AttributeValueMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionImpactMother.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/QuestionMother.java
> FAC-506:fix:Fix calclulate attribute score bug

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaEntity.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/assessmentinvitee/AssessmentInviteeJpaRepository.java
- flickit-assessment-data/src/main/resources/liquibase/changelog-0.25.xml
- flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
> FAC-515: Create assessment invitee table

- flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCaseParamTest.java
> Fac 528 add email validation to get user by email api

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidenceMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidence/EvidencePersistenceJpaAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidence/GetEvidenceListUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidence/GetEvidenceListServiceTest.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaEntity.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/evidence/EvidenceWithAttachmentsCountView.java
> FAC-509: feat: Add attachmentsCount to the result of evidenceList

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermission.java
- flickit-assessment-common/src/test/java/org/flickit/assessment/common/application/domain/assessment/AssessmentPermissionTest.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/AssessmentUserRole.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessment/ReportAssessmentUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeValueExcelService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeValueExcelServiceTest.java
> Fac 545 add exportable to assessment report service

- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/adapter/jpa/MaturityLevelJpaEntityMother.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/maturitylevel/MaturityLevelJpaEntity.java
- flickit-assessment-data/src/main/resources/liquibase/changelog-0.26.xml
- flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelMapper.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/maturitylevel/MaturityLevelPersistenceJpaAdapter.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/domain/MaturityLevel.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersister.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersister.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/create/impl/MaturityLevelCreateKitPersisterTest.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/application/service/assessmentkit/update/impl/MaturityLevelUpdateKitPersisterTest.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/MaturityLevelMother.java
- flickit-assessment-kit/src/test/java/org/flickit/assessment/kit/test/fixture/application/dsl/MaturityLevelDslModelMother.java
> FAC-531:feature:Add description to maturity level

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/FileProperties.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/openai/OpenAiAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/CreateAssessmentAttributeAiReportUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/CreateAssessmentAttributeAiReportServiceTest.java
- flickit-assessment-core/src/test/resources/postman/flickit-assessment-core.postman_collection.json
> Fac 534 create ai report 2

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/questionnaire/QuestionnaireMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/QuestionnaireListItem.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/questionnaire/GetAssessmentQuestionnaireListServiceTest.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireJpaRepository.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionnaire/QuestionnaireListItemView.java
> FAC-546 Add questionnaire description to questionnaire list item

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaEntity.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
- flickit-assessment-data/src/main/resources/liquibase/changelog-0.27.xml
- flickit-assessment-data/src/main/resources/liquibase/changelog-master.xml
> FAC-544: Create attribute insight table

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/CreateAttributeValueExcelService.java
> FAC-550:fix:Fix NPE for notApplicable answers in CreateAttributeValueExcelService

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/report/LoadAssessmentReportInfoAdapter.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/report/AssessmentReportItem.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/assessment/ReportAssessmentServiceTest.java
> FAC-549 Add kit's 'about' to assessment report service output

- dev/dsl-parser/docker-compose.yml
- pom.xml
> Fac 551 upgrade minio

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/answerhistory/AnswerHistoryMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerService.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/answerhistory/GetAnswerHistoryListService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/answer/SubmitAnswerServiceTest.java
> FAC-555 Fix duplicate values in output of answer history list service

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/error/ErrorMessageKey.java
- flickit-assessment-common/src/main/resources/i18n/messages_en.properties
- flickit-assessment-common/src/main/resources/i18n/users/messages_en.properties
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/InviteAssessmentUserUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/common/ErrorMessageKey.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/port/in/assessmentinvitee/InviteAssessmentUserUseCaseParamTest.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/spaceuseraccess/AddSpaceMemberUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/spaceuseraccess/InviteSpaceMemberUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/CreateUserUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCase.java
- flickit-assessment-users/src/main/java/org/flickit/assessment/users/common/ErrorMessageKey.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/spaceuseraccess/AddSpaceMemberUseCaseParamTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/spaceuseraccess/InviteSpaceMemberUseCaseParamTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/CreateUserUseCaseParamTest.java
- flickit-assessment-users/src/test/java/org/flickit/assessment/users/application/port/in/user/GetUserByEmailUseCaseParamTest.java
> FAC-548: bug fix email ignore case

- .github/workflows/ci-cd.yml
- pom.xml
> FAC-556 enable sonar

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/kit/maturitylevel/MaturityLevelMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/domain/MaturityLevel.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/subject/ReportSubjectService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/test/fixture/application/MaturityLevelMother.java
> FAC-558: feat : Add MaturityLevel's description AssessmentReportService

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/adapter/out/persistence/evidenceattachment/EvidenceAttachmentMapper.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/evidenceattachment/GetEvidenceAttachmentsUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/evidenceattachment/LoadEvidenceAttachmentsPort.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/evidenceattachment/GetEvidenceAttachmentsService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/evidenceattachment/GetEvidenceAttachmentsServiceTest.java
> FAC-567:feature:Add creation time to evidence attachment list item

- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/NotificationSenderConfig.java
- flickit-assessment-common/src/main/java/org/flickit/assessment/common/config/NotificationSenderProperties.java
- flickit-assessment-server/src/main/resources/application-dev.properties
> FAC-570:feature:Add base url to notification Sender properties

- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/in/attribute/GetAttributeInsightUseCase.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/port/out/attributeinsight/UpdateAttributeInsightPort.java
- flickit-assessment-core/src/main/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightService.java
- flickit-assessment-core/src/test/java/org/flickit/assessment/core/application/service/attribute/GetAttributeInsightServiceTest.java
- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/core/attributeinsight/AttributeInsightJpaRepository.java
> FAC-577: add is valid to ai insight

- flickit-assessment-data/src/main/java/org/flickit/assessment/data/jpa/kit/questionimpact/QuestionImpactJpaRepository.java
- flickit-assessment-kit/src/main/java/org/flickit/assessment/kit/adapter/out/persistence/questionimpact/QuestionImpactPersistenceJpaAdapter.java
> FAC-584:fix:Fix questionImpact not found error on kit update
